services:
  da:
    image: golang:1.22-alpine
    container_name: da
    entrypoint: ["sh", "-c"]
    command:
      - |
        apk add curl perl jq bash git make
        curl -sSL https://rollkit.dev/install-local-da.sh -o start.sh
        sed -i '\''s|./build/local-da|./build/local-da -listen-all|'\'' start.sh
        bash start.sh
    ports:
      - 7980:7980
  localwasm:
    image: localwasm
    container_name: localwasm
    build:
      context: ../../wasmd
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c"]
    command:
      - |
        apt-get update && apt-get install -y curl perl jq netcat
        until nc -z -v da 7980; do
          echo "Waiting for the DA layer to start..."
          sleep 2
        done
        curl -sSL https://rollkit.dev/cosmwasm/init.sh | \
        perl -pe '\''s/127\.0\.0\.1/0.0.0.0/g'\'' | \
        perl -pe '\''s|http://localhost:7980|http://da:7980|g'\'' | \
        perl -pe '\''s|--rollkit.aggregator|--rollkit.aggregator --api.address tcp://0.0.0.0:1317|g'\'' | \
        bash
    ports:
      - 36657:36657
      - 1317:1317
      - 9290:9290
  relayer:
    container_name: hpl-relayer
    image: gcr.io/abacus-labs-dev/hyperlane-agent:8a66544-20240530-111322
    platform: linux/amd64
    user: root
    # restart: always
    entrypoint: ["sh", "-c"]
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/relayer.json" \
          ./relayer
    ports:
      - 9110:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./relayer:/etc/data
      - ./validator:/etc/validator

  validator-localwasm:
    container_name: hpl-validator-localwasm
    image: gcr.io/abacus-labs-dev/hyperlane-agent:8a66544-20240530-111322
    platform: linux/amd64
    user: root
    # restart: always
    entrypoint: ["sh", "-c"]
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/validator.localwasm.json" \
          ./validator
    ports:
      - 9120:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./validator:/etc/validator
      - ./validator/localwasm:/etc/data

  validator-strideinternal1:
    container_name: hpl-validator-strideinternal1
    image: gcr.io/abacus-labs-dev/hyperlane-agent:8a66544-20240530-111322
    platform: linux/amd64
    user: root
    # restart: always
    entrypoint: ["sh", "-c"]
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/validator.strideinternal1.json" \
          ./validator
    ports:
      - 9121:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./validator:/etc/validator
      - ./validator/strideinternal1:/etc/data
