name: Check Markdown links

on: 
  # This workflow requires pull_request and won't work with pull_request_target 
  # due to github permissions 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1